# Exercise 3: Numpy

Perform the follwing tasks:


In [13]:
#3.1: import the numpy library
import numpy as np

In [14]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.92681297, 0.93063868, 0.41323482, 0.60969922, 0.46617044,
        0.83844777, 0.45022625, 0.61116126, 0.43065531, 0.84425709],
       [0.06360522, 0.21080348, 0.05539288, 0.3445529 , 0.79425781,
        0.58848607, 0.75780372, 0.08168053, 0.89196697, 0.50057291],
       [0.68884548, 0.36717534, 0.30809602, 0.32393648, 0.10277209,
        0.19678646, 0.29593839, 0.85284728, 0.36466931, 0.45136662],
       [0.59204123, 0.3519429 , 0.5523615 , 0.28243004, 0.20826691,
        0.55056337, 0.45412335, 0.27576968, 0.13103234, 0.29194738],
       [0.95973488, 0.96892783, 0.55563707, 0.25044309, 0.06343156,
        0.13493046, 0.62076433, 0.8622263 , 0.25977921, 0.4835825 ],
       [0.51122748, 0.31581559, 0.20376802, 0.34330235, 0.78848033,
        0.8178162 , 0.53240826, 0.60499405, 0.52095884, 0.66028499],
       [0.67635015, 0.8955945 , 0.78423949, 0.5293816 , 0.76027797,
        0.9737237 , 0.55544469, 0.30287844, 0.26825101, 0.51046966],
       [0.03161817, 0.19682086, 0.1778139

In [15]:
#3.3: return only the odd rows of A
A[0:10:2,:] # start:stop:stepsize , all

array([[0.92681297, 0.93063868, 0.41323482, 0.60969922, 0.46617044,
        0.83844777, 0.45022625, 0.61116126, 0.43065531, 0.84425709],
       [0.68884548, 0.36717534, 0.30809602, 0.32393648, 0.10277209,
        0.19678646, 0.29593839, 0.85284728, 0.36466931, 0.45136662],
       [0.95973488, 0.96892783, 0.55563707, 0.25044309, 0.06343156,
        0.13493046, 0.62076433, 0.8622263 , 0.25977921, 0.4835825 ],
       [0.67635015, 0.8955945 , 0.78423949, 0.5293816 , 0.76027797,
        0.9737237 , 0.55544469, 0.30287844, 0.26825101, 0.51046966],
       [0.79512018, 0.78504245, 0.41835172, 0.16196699, 0.86829336,
        0.26448235, 0.75025516, 0.1062293 , 0.76799036, 0.07456543]])

In [16]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[4.66233211, 2.54961591, 2.7104455 , 2.51130847, 3.64280901,
        3.50575714, 4.25967387, 2.61807609, 3.16207386, 2.01779436],
       [2.54961591, 2.77454663, 1.29246833, 1.35885203, 1.52677984,
        2.58427103, 2.57499029, 2.12466545, 2.43990683, 1.68406796],
       [2.7104455 , 1.29246833, 2.0101144 , 1.47760763, 2.53432601,
        2.04560951, 2.22851737, 1.68360363, 1.7849511 , 1.1629518 ],
       [2.51130847, 1.35885203, 1.47760763, 1.59042139, 2.0692531 ,
        1.90745228, 2.51270454, 1.35626759, 1.8427148 , 1.46800298],
       [3.64280901, 1.52677984, 2.53432601, 2.0692531 , 3.68371608,
        2.46298535, 3.18731659, 1.79504137, 2.68042501, 1.8386062 ],
       [3.50575714, 2.58427103, 2.04560951, 1.90745228, 2.46298535,
        3.16784623, 3.32170979, 2.52580065, 2.60923241, 1.7756968 ],
       [4.25967387, 2.57499029, 2.22851737, 2.51270454, 3.18731659,
        3.32170979, 4.41376796, 2.48110115, 3.26534407, 2.41564043],
       [2.61807609, 2.12466545, 1.6836036

In [17]:
#3.5: compute the matrix inverse of A
A_inv=np.linalg.inv(A)
np.isclose(A.dot(A_inv),np.identity(10))#test for identity AA^-1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [27]:
#same in one line with where
np.where(A>0.5, A/2, A) # np.where(condition, Array to take value if condition is true, Array to take Value if condition is false )

array([[0.46340648, 0.46531934, 0.41323482, 0.30484961, 0.46617044,
        0.41922389, 0.45022625, 0.30558063, 0.43065531, 0.42212855],
       [0.06360522, 0.21080348, 0.05539288, 0.3445529 , 0.3971289 ,
        0.29424304, 0.37890186, 0.08168053, 0.44598349, 0.25028646],
       [0.34442274, 0.36717534, 0.30809602, 0.32393648, 0.10277209,
        0.19678646, 0.29593839, 0.42642364, 0.36466931, 0.45136662],
       [0.29602061, 0.3519429 , 0.27618075, 0.28243004, 0.20826691,
        0.27528169, 0.45412335, 0.27576968, 0.13103234, 0.29194738],
       [0.47986744, 0.48446391, 0.27781854, 0.25044309, 0.06343156,
        0.13493046, 0.31038216, 0.43111315, 0.25977921, 0.4835825 ],
       [0.25561374, 0.31581559, 0.20376802, 0.34330235, 0.39424017,
        0.4089081 , 0.26620413, 0.30249702, 0.26047942, 0.33014249],
       [0.33817507, 0.44779725, 0.39211974, 0.2646908 , 0.38013899,
        0.48686185, 0.27772234, 0.30287844, 0.26825101, 0.25523483],
       [0.03161817, 0.19682086, 0.1778139

In [29]:
# if we need only the values to change:
mask=A>0.5 #generate a mask with indix values
A[mask]/2 #manipulate Array at mask locations



array([0.46340648, 0.46531934, 0.30484961, 0.41922389, 0.30558063,
       0.42212855, 0.3971289 , 0.29424304, 0.37890186, 0.44598349,
       0.25028646, 0.34442274, 0.42642364, 0.29602061, 0.27618075,
       0.27528169, 0.47986744, 0.48446391, 0.27781854, 0.31038216,
       0.43111315, 0.25561374, 0.39424017, 0.4089081 , 0.26620413,
       0.30249702, 0.26047942, 0.33014249, 0.33817507, 0.44779725,
       0.39211974, 0.2646908 , 0.38013899, 0.48686185, 0.27772234,
       0.25523483, 0.27523995, 0.33912637, 0.31269199, 0.42569187,
       0.30483622, 0.39756009, 0.39252123, 0.43414668, 0.37512758,
       0.38399518, 0.40649184, 0.34612664, 0.4282519 ])

In [20]:
#or even simpler
A[A>0.5]/2

array([0.46340648, 0.46531934, 0.30484961, 0.41922389, 0.30558063,
       0.42212855, 0.3971289 , 0.29424304, 0.37890186, 0.44598349,
       0.25028646, 0.34442274, 0.42642364, 0.29602061, 0.27618075,
       0.27528169, 0.47986744, 0.48446391, 0.27781854, 0.31038216,
       0.43111315, 0.25561374, 0.39424017, 0.4089081 , 0.26620413,
       0.30249702, 0.26047942, 0.33014249, 0.33817507, 0.44779725,
       0.39211974, 0.2646908 , 0.38013899, 0.48686185, 0.27772234,
       0.25523483, 0.27523995, 0.33912637, 0.31269199, 0.42569187,
       0.30483622, 0.39756009, 0.39252123, 0.43414668, 0.37512758,
       0.38399518, 0.40649184, 0.34612664, 0.4282519 ])