# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.randn(10,10)
A

array([[-0.72534719, -0.6993303 ,  0.97990153,  0.2398618 , -0.59004205,
         0.07735761, -1.28930503,  0.91601077, -0.84937416, -0.9315719 ],
       [-1.07924885, -1.82667322, -0.83674404,  0.04509   , -0.26479856,
        -1.47855759,  0.14890768,  1.14075534, -0.77780112, -1.38759704],
       [-0.12629959, -0.28678398,  0.54183233,  0.11534466, -1.32405035,
         1.06134564, -2.42498186,  1.62012196,  1.29230705,  1.16961195],
       [-0.57479294,  2.0697527 ,  2.60958033,  0.20645069,  1.16095698,
        -0.57504043,  1.89123725,  0.20854301, -0.47079215, -0.75097411],
       [ 0.13623489, -0.09935857,  1.3128913 ,  0.9131028 , -1.67812672,
         1.03096389,  0.39828318, -1.34989091,  0.32976516,  0.24780242],
       [-0.07243402,  0.35866937, -0.4400359 ,  0.6726415 ,  0.46711648,
         1.10170764, -0.03976425, -0.28886891,  0.35551882,  0.35549677],
       [-0.87376391, -1.46118769,  0.58526604,  1.31547379, -0.73434562,
         1.52503241,  0.35284874, -0.58680144

In [3]:
#3.3: return only the odd rows of A
A[1::2]

array([[-1.07924885, -1.82667322, -0.83674404,  0.04509   , -0.26479856,
        -1.47855759,  0.14890768,  1.14075534, -0.77780112, -1.38759704],
       [-0.57479294,  2.0697527 ,  2.60958033,  0.20645069,  1.16095698,
        -0.57504043,  1.89123725,  0.20854301, -0.47079215, -0.75097411],
       [-0.07243402,  0.35866937, -0.4400359 ,  0.6726415 ,  0.46711648,
         1.10170764, -0.03976425, -0.28886891,  0.35551882,  0.35549677],
       [-0.25211759,  0.70518284,  0.57643207, -1.26666955,  0.36507549,
        -1.07184602, -1.83924915, -0.28999614,  0.43977198, -0.4246939 ],
       [ 0.14352434,  0.80248099,  0.90205934, -0.0735018 ,  0.67016527,
         0.61948791,  1.47007675,  0.52942792,  1.72529966, -1.51126844]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
A * A.T

array([[ 0.52612854,  0.75475142, -0.12376116, -0.13787087, -0.08038431,
        -0.00560332,  1.12654821, -0.23094243, -0.85857328, -0.13370324],
       [ 0.75475142,  3.33673504,  0.23996479,  0.09332515,  0.02631001,
        -0.53031332, -0.21758207,  0.8044411 , -0.94553319, -1.11352025],
       [-0.12376116,  0.23996479,  0.29358227,  0.30100115, -1.7383342 ,
        -0.46703019, -1.41925954,  0.93389026,  0.72495556,  1.05505938],
       [-0.13787087,  0.09332515,  0.30100115,  0.04262189,  1.06007307,
        -0.38679606,  2.48787303, -0.26415508,  0.2310619 ,  0.05519795],
       [-0.08038431,  0.02631001, -1.7383342 ,  1.06007307,  2.8161093 ,
         0.48158023, -0.2924775 , -0.49281209,  0.47396149,  0.16606858],
       [-0.00560332, -0.53031332, -0.46703019, -0.38679606,  0.48158023,
         1.21375973, -0.06064176,  0.30962299,  0.06598228,  0.22022595],
       [ 1.12654821, -0.21758207, -1.41925954,  2.48787303, -0.2924775 ,
        -0.06064176,  0.12450223,  1.07927404

In [5]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 0.23171975,  0.92808149,  0.21027872, -0.26629646,  1.01423954,
         0.75918302, -0.52198304,  0.06382193,  1.58002046, -0.53729795],
       [-0.12024301, -0.80877658, -0.02939521,  0.32171212, -0.51441635,
        -0.34538642, -0.19339733, -0.37470346, -0.99064599,  0.02858093],
       [ 0.16314548,  0.50521706,  0.12564639,  0.01983744,  0.51245657,
         0.22874108,  0.0666562 ,  0.32576479,  0.7847914 , -0.10660575],
       [-0.18721003,  1.9354814 ,  0.52209485,  0.19561924,  1.55234818,
         2.20628312, -0.63703359,  0.33871191,  1.7247375 , -0.93961936],
       [ 0.09777452,  0.88937283,  0.04540483, -0.09547084,  0.43763715,
         1.06651842,  0.0278287 ,  0.50863629,  1.17073491, -0.22015883],
       [ 0.45794875, -1.34960274, -0.37557876, -0.18947737, -0.94976961,
        -0.90471447,  0.38022251, -0.4190012 , -1.07244558,  0.65338315],
       [-0.17905578, -0.46611708, -0.14310249,  0.07383609, -0.41454032,
        -0.7324493 ,  0.19553957, -0.33802336

In [6]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

# using vectorizing functions
def Div(x):
    if x > 0.5:
        return x / 2
    else:
        return x

div_vec = np.vectorize(Div)
div_vec(A)


array([[-0.72534719, -0.6993303 ,  0.48995076,  0.2398618 , -0.59004205,
         0.07735761, -1.28930503,  0.45800539, -0.84937416, -0.9315719 ],
       [-1.07924885, -1.82667322, -0.83674404,  0.04509   , -0.26479856,
        -1.47855759,  0.14890768,  0.57037767, -0.77780112, -1.38759704],
       [-0.12629959, -0.28678398,  0.27091616,  0.11534466, -1.32405035,
         0.53067282, -2.42498186,  0.81006098,  0.64615353,  0.58480598],
       [-0.57479294,  1.03487635,  1.30479016,  0.20645069,  0.58047849,
        -0.57504043,  0.94561863,  0.20854301, -0.47079215, -0.75097411],
       [ 0.13623489, -0.09935857,  0.65644565,  0.4565514 , -1.67812672,
         0.51548194,  0.39828318, -1.34989091,  0.32976516,  0.24780242],
       [-0.07243402,  0.35866937, -0.4400359 ,  0.33632075,  0.46711648,
         0.55085382, -0.03976425, -0.28886891,  0.35551882,  0.35549677],
       [-0.87376391, -1.46118769,  0.29263302,  0.65773689, -0.73434562,
         0.7625162 ,  0.35284874, -0.58680144

In [15]:
# using mask
C = np.copy(A)
mask = C > 0.5
C[mask] = C[mask] / 2
C

array([[-0.72534719, -0.6993303 ,  0.48995076,  0.2398618 , -0.59004205,
         0.07735761, -1.28930503,  0.45800539, -0.84937416, -0.9315719 ],
       [-1.07924885, -1.82667322, -0.83674404,  0.04509   , -0.26479856,
        -1.47855759,  0.14890768,  0.57037767, -0.77780112, -1.38759704],
       [-0.12629959, -0.28678398,  0.27091616,  0.11534466, -1.32405035,
         0.53067282, -2.42498186,  0.81006098,  0.64615353,  0.58480598],
       [-0.57479294,  1.03487635,  1.30479016,  0.20645069,  0.58047849,
        -0.57504043,  0.94561863,  0.20854301, -0.47079215, -0.75097411],
       [ 0.13623489, -0.09935857,  0.65644565,  0.4565514 , -1.67812672,
         0.51548194,  0.39828318, -1.34989091,  0.32976516,  0.24780242],
       [-0.07243402,  0.35866937, -0.4400359 ,  0.33632075,  0.46711648,
         0.55085382, -0.03976425, -0.28886891,  0.35551882,  0.35549677],
       [-0.87376391, -1.46118769,  0.29263302,  0.65773689, -0.73434562,
         0.7625162 ,  0.35284874, -0.58680144