# Lambda Operators in Python  

For most of our work with ***NumPy*** arrays and ***Pandas*** data-frames, we try to avoid to use loops over the data structures:

* loops are executed at ***Python*** level: 
   * -> slow interpreter and slow memory access 
* most built in ***NumPy*** and ***Pandas*** functionality come from highly (hardware) optimized pre-build libraries
   * offering fast special purpose alternatives for loops
   * and generic operators from functional programming


In [1]:
#example speed comparison
import numpy as np
A = np.random.random((10000,10000))
 

In [2]:
%%time 
for y in range(10000):
    for x in range(10000):
        A[y,x]=A[y,x]*2

CPU times: user 1min 15s, sys: 13.6 ms, total: 1min 15s
Wall time: 1min 15s


In [3]:
%%time
(lambda x:x*2)(A)

CPU times: user 126 ms, sys: 1.91 s, total: 2.04 s
Wall time: 2.13 s


array([[1.86420639, 0.52882453, 3.12947504, ..., 3.46590029, 1.55892437,
        0.96836667],
       [1.82730325, 2.23941468, 1.96197236, ..., 2.74752244, 0.82411111,
        3.31895291],
       [3.20250936, 1.71873035, 2.25829243, ..., 2.5815497 , 3.38309325,
        1.27604408],
       ...,
       [1.04234487, 3.06774232, 1.83038073, ..., 0.99892511, 0.74183089,
        3.64029173],
       [0.70439561, 3.88372221, 0.2460436 , ..., 1.96364629, 3.89916114,
        3.00308664],
       [0.82354095, 0.0874733 , 1.7671043 , ..., 3.04187177, 2.66093442,
        2.01752829]])

## Lambda Functions

***Lambda functions*** (or more general *Lambda Calculus*) is a concept from ***functional programming***:
* each program is a nested sequence of math like function calls
* *Lambda Calculus* is Turing complete 

### Lambda functions in Python
are implemented as *anonymous* functions. Here a basic example: 

In [4]:
#standard paython function (needs def and name)
def identity(x):
    return x

In [5]:
#function call
identity(2)

2

In [7]:
#lambda function: needs no name, directly executed
(lambda x : x)('hallo')

'hallo'

#### Slightly more complicated example:

In [8]:
#stadard function:
def add5(x):
    return x+5

In [9]:
#lambda version - direct evaluation of argument (here 2)
(lambda x: x+5)(7)

12

In [10]:
#lambda functions as callable object
add5 = (lambda x: x+5)
add5(3)

8

Recall: in Python functions can be arguments, just like scalar values
Main advantage: we can use anonymous functions as arguments in other calls, without the need to define it before hand.  

In [11]:
#example target funktion - applies some function to some list
def listOp(aList, aFunction):
    for i in range(len(aList)):
        aList[i]=aFunction(aList[i])
    return aList     

In [12]:
def plusOne(x):
    return x+1 

In [13]:
A=[1,2,3,4]

In [14]:
listOp(A,plusOne)


[2, 3, 4, 5]

In [16]:
#now with a lambda function
listOp(A,(lambda c:c-3))

[1, 2, 3, 4]

#### Lambda functions with more than one argument

In [17]:
myFunc = (lambda x,y,z : x*x+y+z)
myFunc(2,2,2)

8

#### if-else statements in lambda expressions

In [18]:
A=[1,2,3,4]
listOp(A, (lambda x: True if x > 2 else False) )

[False, False, True, True]

In [19]:
A=[1,2,3,4]
listOp(A, (lambda x: 0 if x > 2 else x+1) )

[2, 3, 0, 0]

### Combining ***lambda functions*** with ***Map***
The ***map*** call allows us to directly apply functions **element wise** to container objects (like lists).  

In [20]:
A=[1,2,3,4]
list(map(lambda x:x+1, ))

[2, 3, 4, 5]

In [21]:
#even works for multiple inputs:
A=[2,2,2,2]
B=[1,1,1,1]
C=[1,2,3,4]
list(map(lambda x,y,z : x+y-z, A,B,C)) 

[2, 1, 0, -1]

## Lambda Operators in ***NumPy***


In [22]:
#we can directly apply lambda function on arrays!
import numpy as np
A=np.ones((10,10))
(lambda x:x+1)(A)

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [23]:
#use lambdafunctions in slicing
A[3:6,3:6]=5 #set some pos to 5
A[(lambda x:x==5)(A)]

array([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [24]:
#but this is not really needed - numpy supports this directly
A[A==5]

array([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [25]:
# applying lambda functions on array slices
A[3,:]=(lambda x: x*x)(A[3,:])

In [26]:
A

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 25., 25., 25.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  5.,  5.,  5.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  5.,  5.,  5.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## Lambda Operators in ***Pandas***
***Pandas*** provides the *apply* method, which allows to use lambda functions directly with data-frames.

In [ ]:
#check if notebook runs in colab
import sys
IN_COLAB = 'google.colab' in sys.modules
print('running in Colab:',IN_COLAB)
path='../'
if IN_COLAB:
  #in colab, we need to clone the data from the repo
  !git clone https://github.com/keuperj/DataScienceSS20.git
  path='DataScienceSS20'

In [27]:
import pandas as pd

In [28]:
#Reading CSV file
d=pd.read_csv('../../DATA/weather.csv')

In [29]:
d.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [30]:
#simple pandas selection of all rows where the humidity is higher than 0.9
d[d['Humidity']>0.9]

Formatted Date        Summary Precip Type  \
6      2006-04-01 06:00:00.000 +0200  Partly Cloudy        rain   
53     2006-04-11 05:00:00.000 +0200       Overcast        rain   
54     2006-04-11 06:00:00.000 +0200  Mostly Cloudy        rain   
55     2006-04-11 07:00:00.000 +0200  Mostly Cloudy        rain   
67     2006-04-11 19:00:00.000 +0200          Foggy        rain   
...                              ...            ...         ...   
96407  2016-09-08 02:00:00.000 +0200  Partly Cloudy        rain   
96408  2016-09-08 03:00:00.000 +0200  Partly Cloudy        rain   
96409  2016-09-08 04:00:00.000 +0200  Partly Cloudy        rain   
96433  2016-09-09 04:00:00.000 +0200          Clear        rain   
96435  2016-09-09 06:00:00.000 +0200          Clear        rain   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
6             7.733333                  5.522222      0.95            12.3648   
53           10.694444                 10.694444      0.95            10.4006   
54           11.111111                 11.111111      0.93            12.0106   
55           11.111111                 11.111111      0.93             9.2092   
67            8.800000                  5.294444      0.99            26.5006   
...                ...                       ...       ...                ...   
96407        16.150000                 16.150000      0.93             0.3703   
96408        15.488889                 15.488889      0.93             3.0268   
96409        16.066667                 16.066667      0.93             3.2039   
96433        15.011111                 15.011111      0.93             3.2039   
96435        13.872222                 13.872222      0.93             4.7495   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
6                       259.0           9.9820         0.0   
53                      161.0           6.6976         0.0   
54                      140.0           5.9731         0.0   
55                      103.0          10.8031         0.0   
67                      339.0           2.6565         0.0   
...                       ...              ...         ...   
96407                   160.0          15.1501         0.0   
96408                   359.0          15.1340         0.0   
96409                    19.0          15.1340         0.0   
96433                   341.0          15.8263         0.0   
96435                     0.0          15.8263         0.0   

       Pressure (millibars)                           Daily Summary  
6                   1016.72       Partly cloudy throughout the day.  
53                  1006.59                   Foggy in the evening.  
54                  1006.34                   Foggy in the evening.  
55                  1006.09                   Foggy in the evening.  
67                  1004.99                   Foggy in the evening.  
...                     ...                                     ...  
96407               1019.06       Partly cloudy starting overnight.  
96408               1018.63       Partly cloudy starting overnight.  
96409               1018.24       Partly cloudy starting overnight.  
96433               1014.37  Partly cloudy starting in the morning.  
96435               1014.66  Partly cloudy starting in the morning.  

[21743 rows x 12 columns]

In [31]:
#same with lambda expression
d['Humidity'].apply(lambda x: x +1) 

0        1.89
1        1.86
2        1.89
3        1.83
4        1.83
         ... 
96448    1.43
96449    1.48
96450    1.56
96451    1.60
96452    1.61
Name: Humidity, Length: 96453, dtype: float64

In [32]:
#example if-else
d['Humidity'].apply(lambda x: 0 if x < 0.5 else 1) 

0        1
1        1
2        1
3        1
4        1
        ..
96448    0
96449    0
96450    1
96451    1
96452    1
Name: Humidity, Length: 96453, dtype: int64

In [ ]:
#multiple rows in one expression
d.apply(lambda x: x['Humidity']+x['Temperature (C)'], axis=1) 

In [ ]:
#more complex example
d['myNewRow']=d.apply(lambda x: x['Humidity']+x['Temperature (C)'] if x['Humidity']>0.5 else 0, axis=1) 

In [ ]:
d.head()